### ISSUE TITLE
Test Case 07 : Automated CI install on IKS fails

### ISSUE THREAD

**Issue by deleeuwblue** [IBM/operator-sample-go#101]
**Issue:**
I set up a fresh IKS cluster on VPC.

I ran command:
sh scripts/ci-create-operators-kubernetes.sh database local reset

After a long time, the script looped on this message:

------------------------------------------------------------------------
Status: Running
Running
2022-06-29 09:53:10 Status: operator-database-catalog(Running
Running)
------------------------------------------------------------------------
Status: Running
Running
2022-06-29 09:53:14 Status: operator-database-catalog(Running
Running)
------------------------------------------------------------------------
Status: Running
Running
2022-06-29 09:53:18 Status: operator-database-catalog(Running
Running)
------------------------------------------------------------------------

There are lots of unusual pods in the operators namespace:

deleeuw@uk.ibm.com@Adams-MacBook-Pro operator-database % kubectl get pods -n operators
NAME                                                              READY   STATUS             RESTARTS        AGE
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb022n7j   0/1     Error              8 (5m14s ago)   19m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb0259fs   0/1     CrashLoopBackOff   9 (15s ago)     21m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb027v52   0/1     CrashLoopBackOff   8 (4m57s ago)   20m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02bqcr   0/1     Pending            0               10m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02cclp   0/1     Pending            0               4m14s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02dr77   0/1     Pending            0               6m19s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02h4d6   0/1     CrashLoopBackOff   8 (5m7s ago)    21m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02klbn   0/1     Pending            0               15m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02ldvp   0/1     Pending            0               5m34s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02mdq5   0/1     Pending            0               7m46s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02q5lz   0/1     CrashLoopBackOff   8 (36s ago)     18m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02t988   0/1     Pending            0               42s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02wjnm   0/1     Pending            0               56s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02wlsf   0/1     CrashLoopBackOff   8 (45s ago)     19m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02xf97   0/1     CrashLoopBackOff   7 (3m7s ago)    16m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb02zbv7   0/1     CrashLoopBackOff   7 (5m2s ago)    19m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb042lhm   0/1     Pending            0               8m6s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb045jst   0/1     CrashLoopBackOff   9 (61s ago)     22m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb045np7   0/1     Pending            0               14m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04bdjw   0/1     Pending            0               14m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04c2tw   0/1     CrashLoopBackOff   7 (4m38s ago)   18m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04d5zd   0/1     CrashLoopBackOff   9 (2m14s ago)   23m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04flxq   0/1     CrashLoopBackOff   8 (2m15s ago)   20m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04gmpz   0/1     CrashLoopBackOff   9 (42s ago)     21m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04gqlj   0/1     CrashLoopBackOff   7 (3m11s ago)   17m
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04gxmp   0/1     Pending            0               7m51s
775262e743cf8e28ee6c636a5acc820383ab64ca1201f7d87078bc5fb04hltg   0/1     CrashLoopBackOff   9 (15s ago)     21m
...
...
...
I truncated the output of the command as it was too long for this issue.  There are actually 500+ pods running in the operators namespace
...
...
...
operator-database-catalog-6vw8c                                   1/1     Running            0               24m
operator-database-catalog-vgksd                                   1/1     Running            0               24m

**Comment by thomassuedbroecker** [comment]
@Vishal-Ramani can you please verify the fix

**Comment by Vishal-Ramani** [comment]
Hi @thomassuedbroecker @deleeuwblue 
This issue occurred when we use Kubernetes Version: 1.22.X.
I have installed Kubernetes Version: **1.23.8_1535** now it's working.
