### ISSUE TITLE
Prometheus documentation needs to be updated related to OpenShift and Kubernetes

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM/operator-sample-go#47]
[Documentation here](https://github.com/IBM/operator-sample-go/blob/main/documentation/AppSetupWithOLM.md)

 * `kubectl apply -f prometheus/role-openshift.yaml` does no longer exist
 * `kubectl apply -f prometheus/role-all.yaml` does no longer exist

**Comment by deleeuwblue** [comment]
I made the documentation clearer.  See these commits:

https://github.com/IBM/operator-sample-go/commit/4a0a034506c19389c6f1d475783f3e58a37067ff
https://github.com/IBM/operator-sample-go/commit/a1fea886863a8f6918da9f209899d67957106d14
