### ISSUE TITLE
TestCase 1 related to step 3 - .yaml extension is missing

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM/operator-sample-go#56]
**Issue:**

ERROR:
————
While running the below steps:
```
$ kubectl create namespace database
$ kubectl apply -f config/samples/database.sample_v1alpha1_database.yaml

```
——>.  $ kubectl apply -f config/samples/database.sample_v1alpha1_databasecluster
Got the below error:
Observation: .yaml extension is missing form the file name.
Resolution: Added .yaml extension to my local machine and the file is executed successfully.
          Needs to append .yaml in the documentation of GitHub repository.
Warning:
—————
ERROR:
————-
While deploying Operator-application without OLM…
While executing the below command
$ make deploy IMG="$REGISTRY/$ORG/$IMAGE_APPLICATION_OPERATOR"
Observation: Cert-manager is missing.
            Even though we are running operator withOut OLM, We need to run the script(Automation) scripts/install-required-kubernetes-components.sh, Which includes the installation of Cert-Manager, OLM,Prometheus.
           It could be better to provide mannual commands to install only cert-manager.
Resolution: Ran scripts/install-required-kubernetes-components.sh For now.
After running the script…
It Went to the Infinite loop….

**Link to the documentation:**

https://github.com/IBM/operator-sample-go/blob/main/documentation/DbSetupWithoutOLM.md

**Comment by thomassuedbroecker** [comment]
Try to run "deinstall everything script"  https://github.com/IBM/operator-sample-go/blob/main/scripts/delete-everything-kubernetes.sh and the try again the https://github.com/IBM/operator-sample-go/blob/main/scripts/install-required-kubernetes-components.sh

**Comment by thomassuedbroecker** [comment]
Fix a problem with the delete everything kubernetes script 
https://github.com/IBM/operator-sample-go/commit/a3bd4579cc3c30158c755490667ccbe306c419f6

**Comment by SundeepBinaylal** [comment]
Fixed the problems with the setup script..!!
