### ISSUE TITLE
Test Case-01, Issues on Install-everything-k8s script

### ISSUE THREAD

**Issue by SundeepBinaylal** [IBM/operator-sample-go#59]
**Issue:**
After Deleting everything with delete-everything-on-k8s-script still the install-everything-script is showing OLM is active
**Link to the documentation:**

https://github.com/IBM/operator-sample-go/blob/main/documentation/Prerequisites.md

**Comment by thomassuedbroecker** [comment]
Try to fix the problem with that commit https://github.com/IBM/operator-sample-go/commit/ffe1eefa616b4238bcadfbb7e8650422745a8973

**Comment by thomassuedbroecker** [comment]
Fix with the last commit!
