### ISSUE TITLE
Prereq documentation to run check-prerequisites.sh (from where)?

### ISSUE THREAD

**Issue by aairom** [IBM/operator-sample-go#60]
**Issue:**
First step, in the "prereq" the user must run "sh scripts/check-prerequisites.sh" but no indication in which folder! That comes later in the documentation!

**Link to the documentation:**
https://github.com/IBM/operator-sample-go/blob/main/documentation/Prerequisites.md

**Comment by thomassuedbroecker** [comment]
Fix is done that commit: https://github.com/IBM/operator-sample-go/commit/6a3bd681d25d19a2bfb12f9c129cc258bfe859b3

**Comment by aairom** [comment]
Issue is fixed in the following commit: https://github.com/IBM/operator-sample-go/commit/6a3bd681d25d19a2bfb12f9c129cc258bfe859b3
