### ISSUE TITLE
Documentation: Application Operator - Operator deployed without OLM

### ISSUE THREAD

**Issue by aairom** [IBM/operator-sample-go#66]
**Issue:**
Step: Build and push new image
source ../versions_local.env
should be;
source ../versions.env
**Link to the documentation:**
https://github.com/IBM/operator-sample-go/blob/main/documentation/AppSetupWithoutOLM.md

**Comment by thomassuedbroecker** [comment]
The documentation in that section should reflect and reference the `prereq` how to set the version_local.env.

https://github.com/IBM/operator-sample-go/blob/main/documentation/AppSetupWithoutOLM.md#build-and-push-new-image

**Comment by aairom** [comment]
Issue is fixed in the following commit: https://github.com/IBM/operator-sample-go/commit/6a3bd681d25d19a2bfb12f9c129cc258bfe859b3
