### ISSUE TITLE
Error while running database backup manually

### ISSUE THREAD

**Issue by dptiwari** [IBM/operator-sample-go#71]
**Issue:**

databasebackups.database.sample.third.party "databasebackup-manual" not found

**Link to the documentation:**

https://github.com/IBM/operator-sample-go/tree/main/operator-database-backup

**Comment by thomassuedbroecker** [comment]
@dptiwari https://ibm.ent.box.com/notes/964408711725?s=lydi76fp84yg2fvzqrckezlehu1chi6l ... Skipped Test Cases were not fit in Local Setup Environment. 

Can this issue be closed?

**Comment by thomassuedbroecker** [comment]
@Vishal-Ramani can you please verify the issue?

**Comment by Vishal-Ramani** [comment]
Hi @thomassuedbroecker 
Verified this issue is resolved now.
