### ISSUE TITLE
No Such Host Error while running Database Backup 

### ISSUE THREAD

**Issue by dptiwari** [IBM/operator-sample-go#73]
**Issue:**

Get "http://database-cluster-0.database-service.database:8089/persons": dial tcp: lookup database-cluster-0.database-service.database: no such host

**Link to the documentation:**
https://github.com/IBM/operator-sample-go/tree/main/operator-database-backup

**Comment by dptiwari** [comment]
Test case was not fit for Local Environment

**Comment by thomassuedbroecker** [comment]
@dptiwari The steps  3 4 5 in the test case 03 are OLM steps in the demo documentation are not applicable!
