### ISSUE TITLE
Test case 02- Infinite loop for Installation script on k8s

### ISSUE THREAD

**Issue by SundeepBinaylal** [IBM/operator-sample-go#78]
**Issue:**

Infinite loop running for operatorhubio-catalog in the installation script of k8s
Here is the debugged output:

``` sh 
sundeepbinaylalgolla@Sundeeps-MacBook-Pro operator-sample-go % kubectl get pods -n olm | grep operatorhubio-catalog
operatorhubio-catalog-f7q47         1/1     Running   0          9m34s
operatorhubio-catalog-xfv8c         1/1     Running   0          9m34s
```

**Link to the documentation:**
https://github.com/IBM/operator-sample-go/blob/main/documentation/Prerequisites.md

**Comment by thomassuedbroecker** [comment]
I fixed that in the commit https://github.com/IBM/operator-sample-go/commit/596b0467edebf229d8a4f58d6c8c860967f66bd1 needs to be verified by @SundeepBinaylal

**Comment by thomassuedbroecker** [comment]
Problem is fixed  the commit as agreed with @SundeepBinaylal .
