### ISSUE TITLE
Test Case 02- Error while executing Build and Publish new catalog image steps-DbOperator with OLM

### ISSUE THREAD

**Issue by SundeepBinaylal** [IBM/operator-sample-go#80]
**Issue:**
Error while executing Build and Publish new catalog image steps-DbOperator with OLM

```sh
sundeepbinaylalgolla@Sundeeps-MacBook-Pro operator-database % source ../versions_local.env
sundeepbinaylalgolla@Sundeeps-MacBook-Pro operator-database % ./bin/opm index add --build-tool podman --mode semver --tag "$REGISTRY/$ORG/$IMAGE_DATABASE_OPERATOR_CATALOG" --bundles "$REGISTRY/$ORG/$IMAGE_DATABASE_OPERATOR_BUNDLE"
zsh: no such file or directory: ./bin/opm
```

**Link to the documentation:**
https://github.com/IBM/operator-sample-go/blob/main/documentation/DbSetupWithOLM.md

**Comment by thomassuedbroecker** [comment]
@SundeepBinaylal In this case the automation https://github.com/IBM/operator-sample-go/blob/main/scripts/check-binfiles-for-operator-sdk-projects.sh can be used.

Documentation in script folder: https://github.com/IBM/operator-sample-go/tree/main/scripts#b-setup-of-the-needed-executable-bin-files

Maybe it makes sense to add this to the https://github.com/IBM/operator-sample-go/blob/main/documentation/Prerequisites.md documentation.

**Comment by SundeepBinaylal** [comment]
@thomassuedbroecker Yes that script worked for me.!! Thanks
