### ISSUE TITLE
Test case 10 : Missing documentation to create Route

### ISSUE THREAD

**Issue by deleeuwblue** [IBM/operator-sample-go#83]
For the demo, the setup steps describe that a Route should be manually created to help test the /hello endpoint from a browser.  There should be a link out to another document to describe exactly how to do this, like we did for setting up COS.

**Link to the documentation:**
https://github.com/IBM/operator-sample-go/blob/main/documentation/demo.md

**Comment by dptiwari** [comment]
Created the [Document](https://github.com/IBM/operator-sample-go/blob/main/documentation/creatingHelloRoute.md) for creating hello route in Openshift for /hello api in application-beta namespace and added the link into [Demo.md](https://github.com/IBM/operator-sample-go/blob/main/documentation/demo.md)
