### ISSUE TITLE
Test case 10 : Catalog sources have incorrect namespace scope

### ISSUE THREAD

**Issue by deleeuwblue** [IBM/operator-sample-go#84]
**Issue:**
After running the script sh scripts/demo-openshift-operators.sh app demo reset, new Catalog sources are successfully created for the Application and Database operators.  However, these Catalog sources can only be seen when in namespace OpenShift-operators.  Every other Catalog source has "cluster wide" scope, and our Catalogs should be the same.

See menu Administration->Cluster Settings->OperatorHub

**Link to the documentation:**

**Comment by thomassuedbroecker** [comment]
We need to verify the catalog template definition https://github.com/IBM/operator-sample-go/blob/main/scripts/database-operator-templates/openshift-database-catalogsource-TEMPLATE.yaml @deleeuwblue

**Comment by thomassuedbroecker** [comment]
@deleeuwblue This is the commit that contains the changes I made for the catalog sources: https://github.com/IBM/operator-sample-go/commit/e9d2ff342356651aef672f04491b30b153c39c30

**Comment by deleeuwblue** [comment]
I tested the commit.  The changes caused a failure because the corresponding Subscription resource no longer matches the namespace of the Catalog.  The logs are below.  As discussed with Thomas, I will test making Subscription manually with the correct namespace, before we attempt changing the script.

************************************
 Configure CR samples for the 'database operator'
************************************
docker.io/nheidloff/operator-database-backup:v1.0.114
  image: docker.io/nheidloff/operator-database-backup:v1.0.114
docker.io/nheidloff/database-service:v1.0.114
************************************
 Create OLM yamls
************************************
************************************
 Deploy Database Operator OLM
************************************
error: the namespace from the provided object "openshift-marketplace" does not match the namespace "openshift-operators". You must pass '--namespace=openshift-marketplace' to perform this operation.
subscription.operators.coreos.com/operator-database-v0-0-1-sub created
Error from server (NotFound): catalogsources.operators.coreos.com "operator-database-catalog" not found
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  creationTimestamp: "2022-06-08T14:26:33Z"
  generation: 1
  labels:
    operators.coreos.com/operator-database.openshift-operators: ""
  name: operator-database-v0-0-1-sub
  namespace: openshift-operators
  resourceVersion: "40112"
  uid: a28d0b8e-4a32-4f25-9362-31dbf30c3d9c
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: operator-database
  source: operator-database-catalog
  sourceNamespace: openshift-operators
status:
  catalogHealth:
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: certified-operators
      namespace: openshift-marketplace
      resourceVersion: "37036"
      uid: d0a4cdac-cc93-4ada-86f1-aeed8562577a
    healthy: true
    lastUpdated: "2022-06-08T14:26:34Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: community-operators
      namespace: openshift-marketplace
      resourceVersion: "38978"
      uid: 46c00db8-f4b1-4428-ae0b-6eecc1cdf6f4
    healthy: true
    lastUpdated: "2022-06-08T14:26:34Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-marketplace
      namespace: openshift-marketplace
      resourceVersion: "38979"
      uid: e7d4e25a-a06c-4246-83d1-2b37b171498b
    healthy: true
    lastUpdated: "2022-06-08T14:26:34Z"
  - catalogSourceRef:
      apiVersion: operators.coreos.com/v1alpha1
      kind: CatalogSource
      name: redhat-operators
      namespace: openshift-marketplace
      resourceVersion: "37480"
      uid: 87444a10-9a26-424c-a05d-a8bae1ccaae4
    healthy: true
    lastUpdated: "2022-06-08T14:26:34Z"
  conditions:
  - lastTransitionTime: "2022-06-08T14:26:34Z"
    message: targeted catalogsource openshift-operators/operator-database-catalog
      missing
    reason: UnhealthyCatalogSourceFound
    status: "True"
    type: CatalogSourcesUnhealthy
  - message: 'constraints not satisfiable: no operators found from catalog operator-database-catalog
      in namespace openshift-operators referenced by subscription operator-database-v0-0-1-sub,
      subscription operator-database-v0-0-1-sub exists'
    reason: ConstraintsNotSatisfiable
    status: "True"
    type: ResolutionFailed
  lastUpdated: "2022-06-08T14:26:34Z"
No resources found in openshift-operators namespace.
No resources found in openshift-operators namespace.
No resources found in openshift-operators namespace.

------------------------------------------------------------------------
Check operator-database-catalog
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:26:44 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:26:47 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:26:51 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:26:54 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:26:58 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:02 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:06 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:09 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:13 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:17 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:20 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:24 Status: operator-database-catalog()
------------------------------------------------------------------------
No resources found in openshift-operators namespace.
Status: 
/Users/deleeuw@uk.ibm.com/Documents/Work/Code/operator-sample-go-automationscript/operator-sample-go/scripts/demo-openshift-operator-database.sh: line 207: Unable: command not found
2022-06-08 15:27:28 Status: operator-database-catalog()
------------------------------------------------------------------------

**Comment by deleeuwblue** [comment]
Hi @thomassuedbroecker I did some manual testing.  Please change the template for the Subscription so it specifies the namespaces like this, then everything will work fine.

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: operator-application-v0-0-1-sub
  **namespace: openshift-operators**
spec:
  channel: "alpha"
  installPlanApproval: Automatic
  name: operator-application
  source: operator-application-catalog
  **sourceNamespace: openshift-marketplace**

**Comment by thomassuedbroecker** [comment]
Hi @deleeuwblue, the change is applied to the templates in that commit https://github.com/IBM/operator-sample-go/commit/3f605421aae84bd3990e7f228a00e8140dfb357b

**Comment by thomassuedbroecker** [comment]
I fixed the automation in this commit: https://github.com/IBM/operator-sample-go/commit/8d12a0cbd05f93cad484dd2004f07572435db928 @deleeuwblue

**Comment by deleeuwblue** [comment]
Fixed
