### ISSUE TITLE
Test Case 10 : Application Scaler fails due to missing secrets

### ISSUE THREAD

**Issue by deleeuwblue** [IBM/operator-sample-go#86]
**Issue:**
After setting up the demo environment with the scripts, the Application Scaler cron job is tested with command:

kubectl create job --from=cronjob/application-scaler manuallytriggered -n application-beta

However it fails with this error:

MountVolume.SetUp failed for volume "tokendata" : secret "prometheus-token-secret" not found.

It seems the script did not setup the secret described in the documentation linked below.

FYI, the associated secret prometheus-cert-secret was created successfully.

**Link to the documentation:**
https://github.com/IBM/operator-sample-go/blob/main/documentation/AppSetupWithOLM.md

**Comment by thomassuedbroecker** [comment]
Which name must the  prometheus-token-secret exist? @deleeuwblue 

Code to create the secret in the script automation:
https://github.com/IBM/operator-sample-go/blob/main/scripts/ci-create-operator-application-openshift.sh#L34

**Comment by thomassuedbroecker** [comment]
@deleeuwblue the automation is updated in that commit: https://github.com/IBM/operator-sample-go/commit/b7b1fa29443f0e4fd2419d9f17d5687e558e9146 when you updated the manual documentation we can close that issue.

**Comment by deleeuwblue** [comment]
@thomassuedbroecker I have updated the manual documentation, so I'm closing this issue.

**Comment by deleeuwblue** [comment]
I tested again, the secret prometheus-token-secret was still created in namespace openshift-operators instead of application-beta.  This is because you fixed the problem in ci script, but not demo script. @thomassuedbroecker

**Comment by thomassuedbroecker** [comment]
You are right. I fixed it in this commit: https://github.com/IBM/operator-sample-go/commit/2d7115412ce2967799e23bcd16d1d0e6915b5a6b

**Comment by deleeuwblue** [comment]
Completed Test case 10
