### ISSUE TITLE
Test Case 10 : Delete everything OpenShift script loops forever

### ISSUE THREAD

**Issue by deleeuwblue** [IBM/operator-sample-go#93]
**Issue:**
While testing test case 10 I used the script delete-everything-openshift.sh.  After 2 hours of running, it seems to be stuck in a loop, see logs:

*** Status: openshift-controller-manager-operator
*** Namespace: openshift-controller-manager-operator
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:26 Status: openshift-controller-manager-operator(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-controller-manager
*** Namespace: openshift-controller-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:30 Status: openshift-controller-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-dns-operator
*** Namespace: openshift-dns-operator
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:35 Status: openshift-dns-operator(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-dns
*** Namespace: openshift-dns
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:39 Status: openshift-dns(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-etcd-operator
*** Namespace: openshift-etcd-operator
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:43 Status: openshift-etcd-operator(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: cert-manager
*** Namespace: cert-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:47 Status: cert-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: calico-system
*** Namespace: calico-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:51 Status: calico-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: calico-system
*** Namespace: calico-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:35:55 Status: calico-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: cert-manager
*** Namespace: cert-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:00 Status: cert-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: default
*** Namespace: default
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:04 Status: default(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-cert-store
*** Namespace: ibm-cert-store
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:08 Status: ibm-cert-store(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-observe
*** Namespace: ibm-observe
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:12 Status: ibm-observe(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-odf-validation-webhook
*** Namespace: ibm-odf-validation-webhook
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:16 Status: ibm-odf-validation-webhook(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-system
*** Namespace: ibm-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:21 Status: ibm-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: calico-system
*** Namespace: calico-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:25 Status: calico-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: cert-manager
*** Namespace: cert-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:29 Status: cert-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: default
*** Namespace: default
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:33 Status: default(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-cert-store
*** Namespace: ibm-cert-store
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:37 Status: ibm-cert-store(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-observe
*** Namespace: ibm-observe
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:42 Status: ibm-observe(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-odf-validation-webhook
*** Namespace: ibm-odf-validation-webhook
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:46 Status: ibm-odf-validation-webhook(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-system
*** Namespace: ibm-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:50 Status: ibm-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-node-lease
*** Namespace: kube-node-lease
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:54 Status: kube-node-lease(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-public
*** Namespace: kube-public
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:36:58 Status: kube-public(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-system
*** Namespace: kube-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:03 Status: kube-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: calico-system
*** Namespace: calico-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:07 Status: calico-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: cert-manager
*** Namespace: cert-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:11 Status: cert-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: default
*** Namespace: default
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:16 Status: default(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-cert-store
*** Namespace: ibm-cert-store
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:20 Status: ibm-cert-store(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-observe
*** Namespace: ibm-observe
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:24 Status: ibm-observe(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: calico-system
*** Namespace: calico-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:28 Status: calico-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: cert-manager
*** Namespace: cert-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:32 Status: cert-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: default
*** Namespace: default
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:37 Status: default(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-cert-store
*** Namespace: ibm-cert-store
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:41 Status: ibm-cert-store(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-odf-validation-webhook
*** Namespace: ibm-odf-validation-webhook
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:45 Status: ibm-odf-validation-webhook(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-system
*** Namespace: ibm-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:49 Status: ibm-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-node-lease
*** Namespace: kube-node-lease
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:53 Status: kube-node-lease(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: calico-system
*** Namespace: calico-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:37:58 Status: calico-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: cert-manager
*** Namespace: cert-manager
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:02 Status: cert-manager(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: default
*** Namespace: default
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:06 Status: default(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-cert-store
*** Namespace: ibm-cert-store
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:10 Status: ibm-cert-store(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-observe
*** Namespace: ibm-observe
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:14 Status: ibm-observe(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-odf-validation-webhook
*** Namespace: ibm-odf-validation-webhook
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:19 Status: ibm-odf-validation-webhook(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: ibm-system
*** Namespace: ibm-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:23 Status: ibm-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-node-lease
*** Namespace: kube-node-lease
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:27 Status: kube-node-lease(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-public
*** Namespace: kube-public
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:32 Status: kube-public(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: kube-system
*** Namespace: kube-system
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:36 Status: kube-system(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-apiserver-operator
*** Namespace: openshift-apiserver-operator
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:41 Status: openshift-apiserver-operator(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-apiserver
*** Namespace: openshift-apiserver
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:45 Status: openshift-apiserver(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-authentication-operator
*** Namespace: openshift-authentication-operator
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:50 Status: openshift-authentication-operator(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
*** Status: openshift-authentication
*** Namespace: openshift-authentication
*** Find: operator-application.v0.0.1
*** Status check: operator-application.v0.0.1
clusterserviceversion.operators.coreos.com "operator-application.v0.0.1" deleted
2022-06-10 13:38:54 Status: openshift-authentication(operator-application.v0.0.1) is deleted
------------------------------------------------------------------------
**Link to the documentation:**

**Comment by thomassuedbroecker** [comment]
@deleeuwblue This problem is related to the deletion of installplan and clusterserviceversions in several projects.
I remove deletion to verify if the installplan and clusterserviceversions is no longer needed. 
This is the commit: https://github.com/IBM/operator-sample-go/commit/fe6c748884845022bf3fe9d73f90ca94bcf85ba7

Additional related commits: 
https://github.com/IBM/operator-sample-go/commit/748bad089539ab47a9cafff74a564a3ebeadcb8c
https://github.com/IBM/operator-sample-go/commit/98794957cc1b39a985b32ed50de58def503f79d7
https://github.com/IBM/operator-sample-go/commit/d14f6a55e6949c9550c0f919eed9950236cf8ca3

**Comment by deleeuwblue** [comment]
I tested the uninstall-everything-openshift again, and this time it did not get stuck in a loop.  Closing this issue.
