### ISSUE TITLE
Review the documentation and remove the documentation in the main repository

### ISSUE THREAD

**Issue by thomassuedbroecker** [IBM/operator-sample-go#96]
* Documentation in the main repository
https://github.com/IBM/operator-sample-go/tree/main/documentation

* Documentation in the documentation  repository
https://github.com/thomassuedbroecker/operator-sample-go-documentation

**Comment by deleeuwblue** [comment]
https://github.com/IBM/operator-sample-go/pull/97/commits/45342deb9232d9bbdb3f9c3f6e862a60458318b2
https://github.com/IBM/operator-sample-go/pull/98/commits/e3d8335157029808dedac027356d495d34ce6863

**Comment by deleeuwblue** [comment]
I removed most documentation and refreshed the main README, including a link to the new extended documentation repo: https://ibm.github.io/operator-sample-go-documentation/
